In [1]:

from torch.utils.data import DataLoader

from data.m2or import GS_LF_OR
from dgllife.utils import SMILESToBigraph
from dgllife.utils import CanonicalAtomFeaturizer
from dgllife.utils import SMILESToBigraph

smiles_to_g = SMILESToBigraph(add_self_loop=True, node_featurizer=CanonicalAtomFeaturizer(),
                                edge_featurizer=None)

dataset = GS_LF_OR(smiles_to_graph=smiles_to_g, 
        n_jobs=1, load=True)

Loading previously saved dgl graphs...

In [2]:
from dgllife.utils import ScaffoldSplitter, RandomSplitter

train_set, val_set, test_set = RandomSplitter.train_val_test_split(
    dataset, frac_train=0.8, frac_val=0.1, frac_test=0.1, random_state = 42)

In [3]:
import dgl 
import torch
from utils import collate_molgraphs

In [9]:
data_loader = DataLoader(dataset=dataset, batch_size=64, shuffle=False,
                            collate_fn=collate_molgraphs, num_workers=0)

In [7]:
train_loader = DataLoader(dataset=train_set, batch_size=64, shuffle=True,
                            collate_fn=collate_molgraphs, num_workers=0)

for batch_id, batch_data in enumerate(train_loader):
    idxs, smiles, bg, labels, masks, ids, node_masks = batch_data
    print(idxs)

[1075, 1263, 2066, 704, 2097, 1233, 131, 844, 1102, 533, 5558, 792, 3661, 3333, 4792, 4873, 4462, 668, 5577, 4494, 1181, 1490, 5712, 3085, 506, 873, 4772, 5508, 2519, 3306, 2260, 2983, 3867, 1714, 1121, 1886, 5526, 5856, 3237, 1539, 4615, 2290, 5200, 1034, 4112, 394, 311, 5720, 1712, 2496, 459, 1037, 1600, 2476, 4476, 4535, 2629, 2213, 3096, 3657, 2331, 3434, 780, 331]
[869, 3634, 1400, 5483, 3721, 2801, 1064, 5278, 149, 1536, 896, 5623, 5479, 1176, 5107, 3291, 5481, 275, 5192, 2834, 1649, 5688, 570, 3760, 2715, 2281, 1818, 840, 2848, 1238, 4842, 4626, 2345, 1572, 3858, 3215, 1689, 3678, 5187, 3095, 2441, 88, 2430, 751, 4563, 4607, 4591, 3652, 3739, 2481, 3628, 3403, 5777, 2798, 5178, 2374, 3536, 2649, 5387, 4999, 4791, 4813, 1775, 2239]
[5078, 5125, 2382, 4244, 374, 3653, 5285, 323, 3129, 5723, 5827, 1926, 5132, 215, 5572, 1861, 4001, 4393, 3702, 2727, 594, 4890, 2913, 681, 4209, 990, 4622, 500, 575, 3150, 5458, 2921, 697, 932, 251, 3192, 369, 2670, 1199, 4443, 5795, 4806, 842, 3383, 1007, 5083, 3115, 5665, 3891, 4004, 3741, 4258, 4176, 1808, 3370, 1543, 2460, 5673, 3013, 5681, 1262, 2572, 5398, 2164]
[2420, 3270, 4601, 1561, 4692, 464, 3386, 584, 20, 1580, 37, 3603, 715, 1730, 1017, 1090, 2207, 5662, 3014, 5622, 5823, 5256, 538, 350, 1611, 4557, 2749, 5845, 5433, 1393, 3504, 4803, 4385, 5432, 501, 5494, 69, 2083, 1328, 5837, 940, 1255, 1144, 2231, 1391, 736, 5666, 1553, 1765, 1957, 3352, 218, 1474, 53, 1005, 420, 3188, 63, 3685, 2269, 5045, 4812, 3194, 465]
[1557, 2225, 2440, 4187, 2171, 2096, 2855, 3889, 81, 5059, 4163, 973, 3174, 3193, 480, 4418, 4220, 3311, 1909, 1789, 3988, 1264, 2795, 3220, 5035, 3553, 5686, 182, 411, 897, 651, 904, 2340, 515, 5271, 3250, 887, 1469, 2461, 3058, 5448, 5742, 1411, 2885, 714, 547, 2704, 4523, 3563, 5316, 4073, 158, 4664, 4915, 965, 216, 276, 5597, 4529, 5320, 14, 1425, 660, 2884]
[390, 3245, 2900, 5002, 4888, 2998, 2686, 4561, 3361, 4292, 839, 1210, 4713, 3475, 1549, 5118, 4751, 2706, 521, 2304, 4092, 5657, 2628, 2126, 2640, 3006, 2652, 5195, 5658, 1953, 2545, 478, 2412, 4436, 2425, 5563, 5386, 644, 741, 4263, 589, 4098, 4838, 2450, 3881, 4764, 3819, 377, 1612, 948, 3460, 3997, 1426, 2622, 5715, 1085, 1327, 3488, 4396, 1847, 3610, 4507, 3826, 5728]
[856, 1593, 3936, 1389, 1494, 1266, 4671, 3128, 5703, 949, 5732, 151, 2115, 3565, 281, 5141, 4904, 4416, 2854, 410, 3010, 802, 5709, 4702, 2120, 2633, 3494, 612, 2058, 5369, 2596, 4733, 3908, 2746, 4878, 3732, 763, 5750, 3917, 4943, 5627, 2015, 2351, 1749, 5495, 2312, 5517, 3273, 5490, 5354, 3828, 451, 1892, 5684, 1127, 5707, 5687, 472, 2295, 2170, 2356, 4790, 1974, 908]
[1768, 4800, 5473, 86, 1452, 1135, 2787, 2948, 5682, 987, 240, 2609, 452, 2347, 426, 3263, 4832, 5521, 2024, 3163, 1559, 5202, 1133, 3232, 4011, 3874, 642, 1251, 2513, 5816, 2940, 2223, 2607, 3414, 3642, 444, 885, 1786, 3679, 3362, 3359, 3492, 2532, 2939, 3258, 615, 875, 2937, 1221, 3004, 2238, 2856, 1552, 3979, 3738, 4696, 2876, 4794, 5690, 3662, 3378, 2980, 1432, 4700]
[3575, 581, 997, 2014, 1546, 2638, 1781, 2370, 4585, 677, 3699, 234, 1774, 1519, 4600, 1589, 5502, 3673, 1897, 3518, 4572, 4219, 5224, 4248, 4137, 3837, 3656, 2163, 1089, 1966, 2518, 1846, 4135, 2176, 278, 818, 1004, 3538, 1110, 4648, 5501, 3231, 1983, 4267, 2697, 1080, 1832, 1382, 2639, 549, 2154, 1826, 5102, 4881, 1117, 3322, 3902, 2088, 2924, 1003, 5853, 4900, 5771, 1584]
[705, 4311, 2057, 1379, 3839, 2157, 694, 3742, 1771, 5454, 4629, 5605, 172, 3761, 3000, 4265, 3075, 1259, 1464, 129, 2323, 4207, 4467, 661, 747, 204, 5366, 3241, 752, 3209, 2268, 3844, 5095, 2564, 3774, 3143, 1879, 551, 2887, 4680, 106, 3392, 4318, 2714, 952, 5540, 2085, 2677, 5030, 5335, 348, 1907, 4463, 2144, 4461, 2436, 3429, 3558, 3034, 5755, 4256, 3388, 3509, 5328]
[2077, 401, 503, 1002, 820, 2478, 1608, 4944, 5380, 4983, 850, 3458, 5091, 4233, 5619, 4339, 2419, 3043, 4776, 4446, 2672, 2768, 1232, 5394, 5017, 5815, 1952, 495, 554, 195, 5468, 1744, 4153, 1509, 1441, 2016, 35, 3268, 652, 5344, 3478, 74, 1989, 4274, 3740, 4313, 310, 3895, 4151, 5043, 5277, 4590, 2580, 5625, 1451, 2042, 3353, 3824, 1162, 3542, 2543, 482, 1099, 2186]
[328, 4795, 188, 1158, 4511, 2517, 2052, 1187, 5040, 3586, 4906, 806, 5804, 2754, 5571, 1670, 3751, 2063, 3336, 1763, 4121, 1026, 4247, 259, 2784, 2592, 3265, 4643, 1688, 3836, 4596, 2162, 1435, 3179, 5759, 2258, 750, 1272, 1125, 1222, 1622, 4280, 212, 236, 633, 1751, 4221, 773, 2159, 3290, 5529, 707, 3734, 3916, 5482, 2678, 1666, 2631, 5230, 1514, 996, 5348, 3153, 5084]
[4746, 3592, 2453, 910, 3466, 5314, 1595, 1226, 367, 4333, 3321, 3160, 5333, 886, 1027, 3447, 4340, 1831, 3407, 1915, 4588, 590, 4502, 1463, 2078, 1134, 4239, 898, 5820, 2497, 4286, 4819, 3615, 2791, 1219, 672, 5821, 1418, 1830, 5654, 208, 486, 2789, 4052, 573, 3882, 3468, 1213, 779, 4141, 3102, 5745, 2273, 794, 1299, 1112, 2264, 1736, 542, 3901, 4354, 4224, 4189, 2471]
[3912, 1274, 4024, 2603, 3883, 3197, 4952, 4084, 4334, 4993, 3315, 1963, 1803, 403, 5295, 5197, 1067, 1912, 2335, 3618, 4124, 5817, 4879, 915, 1654, 1040, 3973, 4763, 166, 68, 5250, 5811, 5317, 2515, 1364, 2432, 2256, 5065, 3489, 3547, 1055, 4281, 2868, 985, 4579, 3025, 2726, 3366, 1820, 3868, 3938, 1297, 2400, 469, 4959, 4195, 1578, 4047, 3688, 3337, 4205, 1260, 4271, 3704]
[2605, 2804, 1239, 4814, 1675, 2123, 3948, 2229, 1888, 649, 4974, 2680, 2428, 3780, 3181, 4628, 1750, 565, 3649, 429, 4006, 58, 5560, 5223, 1115, 2682, 3768, 3918, 5166, 2864, 4855, 5306, 5516, 1192, 1010, 286, 3217, 1443, 360, 4938, 1876, 5462, 2235, 5109, 1721, 1475, 4310, 4753, 3145, 1594, 1417, 4034, 5293, 1727, 1097, 516, 3064, 112, 1634, 4616, 4740, 1609, 5179, 1334]
[3379, 4694, 811, 1988, 2740, 2654, 3365, 2257, 159, 4111, 1283, 2920, 3176, 5149, 4608, 4216, 4874, 5120, 1376, 2185, 776, 3116, 1035, 2608, 2683, 222, 1174, 1805, 3424, 3382, 545, 2929, 5440, 4802, 557, 3779, 529, 2736, 588, 3390, 4381, 1029, 2037, 1868, 2442, 373, 2155, 4504, 2679, 1246, 1180, 144, 4257, 3318, 3508, 893, 5312, 1197, 1462, 686, 179, 101, 680, 1690]
[531, 2671, 841, 5240, 2113, 1477, 5760, 2875, 5355, 5573, 1405, 798, 3893, 4370, 2019, 4525, 4589, 2357, 3811, 4345, 439, 2852, 1669, 4951, 962, 2494, 3207, 3684, 291, 2554, 3411, 1103, 1123, 5624, 266, 1507, 2503, 150, 4148, 5039, 5087, 396, 4609, 4075, 3377, 3028, 3638, 5510, 4259, 193, 3670, 5050, 1829, 3091, 1453, 3759, 5438, 5566, 4981, 1660, 890, 2311, 560, 4687]
[3941, 1621, 2208, 4669, 87, 3210, 5726, 1864, 4758, 2182, 3477, 5565, 3633, 1520, 4811, 1925, 2121, 1193, 1946, 4717, 3532, 4435, 2166, 929, 4522, 1339, 5228, 1932, 2402, 2949, 5794, 1212, 4272, 4039, 5603, 2194, 5011, 5766, 2776, 3257, 1630, 3982, 3566, 5659, 5359, 4423, 4355, 4742, 1414, 5158, 1711, 36, 4157, 4204, 1234, 969, 5103, 5639, 2333, 2305, 4023, 1467, 1710, 4634]
[2288, 2707, 1624, 2408, 4513, 436, 1152, 2464, 24, 1111, 2314, 3066, 4762, 4817, 2384, 3764, 3944, 4264, 5374, 1798, 1456, 829, 338, 1442, 2267, 5081, 1617, 2667, 3963, 3437, 3185, 2469, 755, 3873, 2951, 3055, 3541, 4040, 82, 1228, 3972, 2566, 1098, 4127, 4912, 4730, 4174, 999, 3953, 121, 1421, 2167, 47, 1230, 1163, 3998, 2149, 1704, 561, 5274, 4194, 4919, 739, 913]
[4013, 4439, 5774, 1560, 611, 5725, 3094, 935, 1665, 1683, 1001, 28, 2195, 2447, 5705, 2606, 2313, 1940, 1129, 2131, 2321, 3959, 790, 3864, 3035, 625, 610, 4375, 5751, 4456, 5752, 2602, 2559, 1737, 3928, 587, 324, 1878, 1708, 2569, 5101, 2946, 5028, 4860, 1709, 353, 5628, 2642, 1776, 2372, 3745, 3097, 3007, 3357, 4701, 693, 3126, 1412, 1305, 5471, 2630, 3224, 2067, 92]
[3523, 2353, 1927, 3689, 5522, 5212, 1326, 3360, 4094, 1113, 91, 3355, 4307, 4470, 711, 720, 4745, 2810, 5834, 4129, 3697, 4498, 4166, 1922, 974, 1446, 3109, 4190, 2266, 4352, 585, 5220, 17, 2827, 3083, 4222, 398, 1522, 3295, 5808, 4534, 857, 1884, 5779, 4122, 4549, 368, 442, 2117, 5146, 1902, 3395, 4410, 481, 250, 1993, 1286, 1851, 4091, 5492, 2753, 1337, 3691, 4610]
[1889, 107, 4460, 1323, 2084, 5266, 1936, 227, 1950, 1149, 1809, 5183, 3020, 3799, 2788, 3042, 1939, 3155, 2978, 938, 4518, 1359, 1506, 1206, 490, 756, 1245, 1980, 4768, 568, 1653, 5574, 4051, 1020, 3033, 1773, 3528, 4392, 4604, 4323, 4368, 968, 4916, 609, 3909, 826, 3569, 2623, 3288, 3076, 446, 2001, 5171, 1380, 3484, 4447, 2943, 947, 4374, 4909, 5487, 2669, 4020, 219]
[2610, 518, 5322, 4471, 1491, 960, 4885, 1814, 2877, 4109, 4159, 882, 2277, 2881, 4133, 5397, 4755, 4328, 3667, 1772, 1562, 443, 5525, 2344, 5780, 4440, 4539, 5713, 2360, 3274, 3307, 3980, 5531, 273, 1575, 5284, 2377, 5792, 964, 2867, 2483, 5417, 165, 4987, 4728, 1764, 3879, 4296, 883, 3786, 5145, 4505, 2873, 5764, 643, 4417, 152, 3968, 2846, 3877, 244, 1392, 1151, 5553]
[622, 5259, 330, 4724, 4065, 1201, 287, 3017, 421, 4081, 1896, 306, 3872, 5079, 2069, 5247, 4750, 4022, 3347, 4005, 2253, 540, 132, 4183, 3539, 3516, 5549, 2711, 945, 226, 1357, 2463, 4260, 1591, 2847, 819, 105, 1444, 210, 4295, 300, 3456, 2398, 2448, 874, 3607, 1039, 2101, 128, 4674, 1022, 3784, 2578, 4457, 5227, 1386, 1960, 2359, 2799, 1208, 2175, 5456, 5443, 1057]
[5243, 4275, 1706, 347, 1168, 1423, 3605, 4235, 5061, 1681, 157, 4108, 1943, 3757, 1074, 1596, 3505, 1898, 186, 2655, 3513, 4908, 1237, 23, 4167, 5071, 4074, 1220, 5772, 2073, 2361, 406, 4301, 2689, 2750, 3729, 496, 4284, 3932, 4279, 3479, 5139, 3929, 3173, 11, 5729, 3976, 5216, 1424, 4520, 5341, 5520, 5615, 5297, 471, 5859, 3008, 1850, 2292, 1510, 4483, 4852, 2032, 5239]
[3443, 1657, 2659, 3630, 4434, 4104, 1361, 2493, 1627, 3911, 3332, 2044, 309, 4331, 3647, 2598, 3580, 271, 5670, 4105, 5680, 5727, 1227, 566, 2091, 855, 2080, 520, 3428, 2837, 4357, 3351, 3254, 3426, 4118, 1108, 665, 1951, 352, 5671, 2364, 3114, 2752, 1551, 5251, 267, 4826, 4431, 743, 1754, 4997, 5362, 5731, 3964, 1229, 2780, 7, 5379, 4844, 1345, 2068, 813, 4653, 5459]
[5180, 726, 731, 2330, 4877, 21, 3161, 2994, 356, 4350, 3910, 3543, 5513, 134, 1362, 1038, 3937, 2650, 789, 272, 4675, 4994, 5119, 1743, 4652, 4450, 2140, 977, 5012, 4647, 60, 49, 5476, 4899, 4409, 3570, 3807, 5176, 2414, 3611, 5055, 889, 4961, 1204, 5466, 700, 4086, 4949, 2230, 5633, 2719, 2687, 2620, 5470, 4421, 2705, 2755, 1537, 4840, 3800, 3641, 1656, 1177, 4128]
[4405, 386, 3038, 1569, 3714, 4383, 3651, 2172, 198, 1374, 5554, 5414, 4827, 1410, 2289, 555, 5601, 2800, 983, 4114, 1241, 2119, 4872, 1833, 1550, 3920, 4898, 3783, 630, 2710, 1756, 5208, 381, 2407, 5561, 5491, 4172, 4165, 3752, 2526, 2410, 4672, 4169, 1278, 1582, 5391, 2465, 3899, 5047, 3455, 5252, 5444, 383, 3957, 5852, 3309, 2865, 3303, 1579, 2109, 4818, 1545, 5221, 4853]
[4173, 4287, 3855, 2320, 196, 4747, 4010, 1420, 4253, 2902, 2617, 3289, 312, 1933, 3870, 1011, 1961, 2426, 4617, 2942, 2696, 3065, 3790, 3624, 304, 2259, 2248, 4633, 1136, 4161, 2653, 4012, 2531, 619, 5674, 1454, 2306, 2031, 102, 454, 5319, 1383, 2813, 3805, 2366, 3106, 2641, 4586, 44, 438, 79, 2851, 4545, 3334, 730, 972, 4480, 5405, 2389, 5098, 5294, 2467, 1602, 2429]
[2252, 3023, 4390, 1203, 5591, 4526, 1501, 2373, 1511, 596, 5621, 3557, 370, 1812, 4655, 1159, 2895, 1515, 183, 2794, 5570, 2287, 1236, 579, 2541, 3663, 290, 4320, 346, 3914, 1640, 2584, 3412, 5363, 3308, 1429, 1787, 1532, 415, 812, 1182, 1521, 3320, 1504, 4306, 3127, 2509, 4676, 4168, 2488, 2812, 4251, 4927, 4847, 3196, 274, 577, 485, 4578, 2619, 135, 2456, 1739, 1051]
[5537, 1307, 3664, 1492, 3631, 1822, 2089, 447, 803, 3151, 2452, 4967, 2874, 2769, 4839, 903, 4372, 4449, 845, 2822, 3162, 2843, 3003, 5236, 2242, 277, 5115, 450, 3203, 3711, 4472, 3154, 5796, 3213, 4308, 3138, 4152, 5710, 2480, 3123, 4880, 3089, 3776, 4998, 118, 4532, 2986, 2906, 3211, 4063, 5153, 2694, 2434, 1175, 4871, 2892, 4577, 591, 491, 2514, 5484, 1869, 1165, 4181]
[1956, 2927, 2647, 2984, 211, 1913, 597, 3078, 1071, 2737, 5281, 2821, 3248, 3945, 3534, 2241, 1692, 5339, 3706, 4050, 4085, 359, 1050, 546, 5413, 3473, 2033, 3722, 4689, 399, 3239, 4477, 18, 5775, 5737, 3861, 1373, 5099, 3787, 801, 113, 4815, 2972, 1967, 5207, 1000, 4552, 1268, 618, 4388, 1447, 185, 2663, 194, 279, 1335, 5840, 808, 4825, 3814, 1703, 1068, 916, 2187]
[468, 2319, 4420, 3886, 1910, 5580, 73, 888, 1315, 3562, 339, 1473, 5806, 1487, 1606, 1588, 5013, 1049, 4193, 3690, 1641, 3537, 3178, 138, 3939, 1367, 4044, 4614, 4767, 3483, 313, 1397, 1524, 5352, 3422, 2381, 3590, 141, 4698, 4756, 397, 1137, 2145, 2209, 100, 3576, 5218, 3081, 4366, 5754, 4236, 2299, 1991, 586, 4384, 5784, 2820, 624, 3700, 1717, 2741, 4771, 2211, 745]
[5057, 3617, 2886, 1873, 5282, 1766, 148, 3718, 4478, 1351, 925, 2474, 5402, 2325, 3246, 541, 2535, 2908, 5336, 2317, 3319, 2699, 2169, 5062, 2090, 5612, 171, 4939, 2114, 4116, 229, 4651, 371, 1804, 4901, 1632, 4546, 4527, 3589, 1948, 5360, 5156, 380, 3463, 1130, 4741, 1590, 319, 4093, 5543, 5324, 1438, 1934, 497, 343, 3788, 1840, 4991, 3598, 1032, 3454, 2899, 2862, 4358]
[1652, 733, 5477, 2215, 2632, 1385, 647, 3415, 1301, 2303, 3591, 3966, 4681, 2334, 4003, 582, 4969, 2451, 5054, 3044, 1691, 3049, 2424, 1752, 1518, 796, 2431, 5019, 5231, 1413, 4584, 4732, 3869, 1919, 2100, 93, 4083, 3773, 2576, 2805, 4619, 605, 4453, 2221, 3545, 326, 1778, 831, 1855, 3986, 696, 3040, 847, 2228, 3358, 3070, 824, 5427, 1290, 2841, 5389, 4599, 2636, 5735]
[1567, 207, 1788, 3650, 5014, 3180, 4789, 867, 2355, 2823, 1309, 1866, 2046, 3716, 3793, 905, 1448, 3620, 5027, 2098, 3674, 2316, 4714, 653, 4245, 859, 45, 978, 3275, 4025, 1395, 958, 4342, 909, 4053, 2665, 2495, 2917, 389, 3978, 5246, 3782, 4787, 640, 1738, 213, 3720, 917, 1793, 1845, 5108, 2548, 3568, 2818, 5701, 5826, 2624, 5074, 5649, 1086, 4210, 288, 5724, 3084]
[5082, 670, 5283, 5844, 2023, 5569, 2437, 4595, 3430, 1347, 4631, 2688, 710, 4593, 4830, 4716, 3552, 2685, 2718, 1782, 5117, 3071, 1800, 3292, 4036, 1592, 4438, 4538, 5814, 2536, 4041, 1450, 4337, 1705, 5836, 258, 5204, 1375, 416, 4556, 376, 2815, 891, 3158, 4038, 5326, 1835, 4550, 1033, 1746, 2072, 2226, 4587, 4536, 2570, 3560, 4099, 2562, 5617, 4293, 3442, 4573, 1261, 2882]
[2280, 1433, 3286, 2012, 5159, 5364, 3601, 1498, 2104, 4229, 2367, 325, 4398, 4228, 703, 5847, 4089, 2567, 2153, 245, 1502, 1644, 1466, 1698, 1713, 2634, 1807, 3271, 1225, 737, 2549, 2107, 5303, 2501, 3915, 4509, 5377, 4325, 4540, 2575, 52, 4442, 3433, 1695, 4217, 5046, 72, 4160, 4895, 5857, 333, 435, 5305, 4454, 5262, 2392, 437, 3924, 4537, 1849, 2857, 2988, 4367, 3041]
[5631, 4008, 2076, 1468, 4864, 2217, 4683, 61, 821, 3485, 3093, 5769, 2555, 169, 3400, 2298, 5358, 8, 5719, 4427, 3806, 1954, 5395, 4145, 5205, 4930, 2220, 1629, 4482, 3259, 3660, 1637, 4376, 5607, 927, 5557, 4884, 4269, 3626, 5036, 1760, 1726, 5702, 4889, 2997, 3144, 4605, 163, 3113, 548, 4709, 3801, 2817, 2637, 5668, 1891, 2732, 1755, 4414, 3750, 3401, 3080, 5424, 4531]
[296, 3249, 1289, 4184, 3101, 5789, 457, 4466, 2224, 2029, 59, 5094, 4635, 2825, 4130, 1320, 2955, 2934, 4266, 3107, 2418, 3821, 5532, 1157, 4707, 3559, 762, 701, 3659, 1735, 5150, 4515, 621, 4349, 2963, 2544, 5144, 5593, 3471, 1716, 877, 1677, 5523, 1223, 1207, 2011, 3501, 3198, 5813, 658, 5584, 2459, 2134, 662, 1052, 2458, 5155, 636, 1534, 4882, 430, 4329, 2553, 2383]
[4923, 4321, 4139, 2990, 5586, 307, 2757, 2486, 2968, 5411, 1436, 2932, 2953, 3770, 5420, 5025, 2271, 4054, 5677, 483, 5638, 5614, 5169, 765, 556, 602, 4500, 1797, 3930, 1258, 4668, 5669, 3871, 1046, 3804, 5741, 4348, 1825, 979, 4002, 5636, 1871, 4315, 3754, 2550, 5137, 5089, 5803, 937, 3955, 1995, 248, 1457, 5273, 1084, 4934, 3593, 5692, 2270, 344, 1489, 2725, 2328, 508]
[214, 3112, 507, 4517, 3992, 1817, 1269, 1303, 2760, 988, 3413, 122, 4783, 1671, 1281, 5437, 2522, 4303, 5077, 1791, 3045, 4743, 1338, 2396, 317, 1019, 3184, 4299, 3599, 5034, 1190, 2614, 1949, 1729, 3727, 180, 2840, 3827, 1725, 4581, 1914, 1211, 1485, 1030, 1140, 167, 1607, 3046, 5500, 5005, 4077, 5407, 1587, 1667, 1061, 2210, 4192, 5474, 3654, 3402, 2137, 3453, 3167, 3833]
[687, 5021, 4734, 5449, 519, 4473, 800, 3408, 2030, 4677, 683, 1459, 5548, 5620, 3375, 26, 1025, 2662, 1170, 641, 32, 866, 4230, 3703, 5219, 4837, 3238, 3975, 4347, 3573, 3606, 5210, 3364, 4180, 837, 564, 4387, 3526, 1265, 1185, 2403, 5711, 3842, 3372, 103, 1179, 834, 3810, 1616, 3491, 3829, 3942, 2601, 2759, 1333, 1655, 2527, 4620, 3125, 3199, 1008, 261, 3077, 1758]
[3765, 4032, 252, 67, 3524, 5018, 788, 5499, 1837, 22, 4989, 2981, 4554, 2059, 1929, 5345, 382, 1924, 5022, 448, 5455, 553, 1042, 5842, 173, 4995, 1647, 231, 5785, 4100, 3694, 2651, 2530, 425, 1576, 4037, 3416, 4327, 598, 1325, 4663, 1224, 682, 1767, 3588, 734, 453, 2002, 2905, 1054, 4966, 1626, 3387, 3018, 3629, 39, 2394, 5165, 3493, 865, 5787, 4076, 1247, 3519]
[2174, 177, 4316, 3233, 1109, 3612, 5445, 1196, 3223, 1870, 4386, 1142, 2094, 3595, 2308, 4201, 3906, 4197, 5818, 3216, 4401, 5435, 5151, 2036, 2764, 4119, 5128, 3015, 1813, 3990, 2664, 2643, 2583, 4781, 1178, 147, 4660, 1313, 5048, 1024, 4941, 4936, 2191, 432, 321, 2173, 4765, 4241, 5185, 674, 1428, 3965, 3749, 2404, 3149, 505, 2499, 5100, 2118, 2765, 230, 5602, 4926, 2283]
[3862, 567, 4945, 879, 5480, 2, 246, 1780, 5683, 3668, 1547, 340, 3795, 852, 2099, 5550, 5242, 5412, 5505, 3243, 3845, 1661, 4309, 424, 4863, 4638, 3692, 5691, 2051, 5699, 3849, 5004, 5304, 1431, 4343, 746, 5342, 1941, 2571, 2007, 2600, 1723, 4543, 4126, 654, 5301, 2763, 50, 4722, 293, 4481, 2274, 3036, 3253, 1610, 4487, 2034, 5385, 1095, 3989, 1977, 1526, 2916, 4182]
[1479, 1883, 868, 4305, 387, 5154, 2040, 4907, 2977, 1740, 4937, 2245, 2025, 3039, 4056, 289, 4031, 3279, 1368, 2177, 342, 721, 4489, 3550, 153, 592, 5576, 676, 2446, 4508, 1143, 2222, 2974, 2966, 5234, 1164, 2586, 349, 5260, 4103, 689, 664, 627, 5583, 4246, 4568, 2506, 1538, 5267, 1799, 3551, 4774, 4346, 1911, 5793, 3625, 322, 3794, 1662, 1517, 4322, 3665, 1295, 4009]
[4562, 5546, 5372, 170, 1947, 1387, 1785, 1126, 4775, 3276, 4048, 400, 5697, 657, 431, 3888, 4288, 1319, 781, 5843, 4990, 1564, 4497, 838, 5058, 5849, 5514, 967, 5175, 783, 5075, 4657, 463, 864, 1404, 1343, 2716, 5457, 509, 2657, 5399, 1094, 526, 1173, 1344, 1566, 3131, 1047, 5545, 4444, 299, 2720, 5478, 1106, 2395, 3470, 3148, 3967, 2168, 4404, 2028, 3469, 1183, 1249]
[5634, 4940, 1355, 3574, 4576, 3725, 5738, 3792, 1701, 1146, 1352, 4918, 1105, 3733, 5198, 648, 2095, 1556, 3934, 4215, 4238, 4448, 4582, 907, 136, 771, 712, 10, 1694, 3856, 4441, 422, 2470, 2183, 1092, 1321, 1370, 3227, 757, 2573, 4071, 5564, 4490, 5736, 517, 3427, 5739, 5704, 3767, 3172, 5748, 799, 5186, 316, 1472, 936, 1476, 3024, 3548, 4211, 3737, 3676, 3329, 1599]
[5589, 4058, 3299, 2021, 76, 5562, 4055, 4761, 4928, 5749, 2803, 203, 2487, 1882, 2196, 5822, 5382, 3781, 2971, 5830, 4125, 4686, 3450, 2646, 5085, 1041, 3090, 3208, 4862, 1244, 2728, 4986, 4395, 3423, 1672, 5032, 4935, 1488, 982, 332, 3133, 3021, 5381, 4371, 5744, 99, 408, 263, 5157, 1881, 2698, 4072, 3404, 4570, 3830, 80, 4336, 96, 5626, 5861, 5126, 2510, 1153, 292]
[2181, 3841, 2354, 1189, 3897, 3182, 1973, 3235, 764, 329, 3323, 4252, 4922, 57, 1905, 2337, 5343, 5020, 3614, 2254, 1288, 1770, 4391, 5008, 4704, 2930, 3853, 458, 4560, 4650, 2644, 5799, 1194, 5376, 4406, 772, 5415, 2828, 3866, 2413, 3817, 3027, 247, 3802, 1271, 5730, 5370, 4437, 578, 3398, 192, 5832, 5272, 1496, 1558, 5507, 5809, 5164, 2009, 3785, 3808, 1499, 4796, 2284]
[1628, 2658, 372, 3921, 2618, 4679, 5189, 1231, 1839, 3970, 1530, 5265, 5350, 5422, 884, 3585, 4645, 5825, 1091, 3195, 2390, 4640, 2179, 3189, 1298, 2691, 981, 4066, 1330, 5846, 27, 1544, 3724, 2552, 3016, 2415, 4419, 3350, 3820, 4087, 84, 1745, 5678, 5160, 1992, 1114, 3393, 2087, 3919, 498, 3053, 1480, 3708, 5588, 2767, 264, 2124, 2661, 3961, 3418, 5645, 4665, 1018, 3529]
[1801, 3715, 3898, 2748, 522, 4988, 2879, 3549, 3896, 777, 3344, 1844, 4690, 1287, 2819, 378, 2240, 4656, 124, 5694, 3639, 1336, 1434, 2378, 1699, 209, 3111, 3671, 2915, 1455, 3499, 4373, 2050, 1235, 1119, 4351, 1650, 2008, 2358, 4240, 351, 46, 5365, 809, 1762, 62, 1535, 3632, 3435, 1341, 3693, 3859, 3201, 2692, 3564, 2197, 175, 2880, 2310, 634, 4850, 628, 1394, 5199]

In [10]:
for batch_id, batch_data in enumerate(data_loader):
    idxs, smiles, bg, labels, masks, ids, node_masks = batch_data
    print(idxs)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]
[64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127]
[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191]
[192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255]
[256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319]
[320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383]
[384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447]
[448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511]
[512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575]
[576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639]
[640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703]
[704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767]
[768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831]
[832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895]
[896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959]
[960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023]
[1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087]
[1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151]
[1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215]
[1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279]
[1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343]
[1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407]
[1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471]
[1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535]
[1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599]
[1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663]
[1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727]
[1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791]
[1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855]
[1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919]
[1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983]
[1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047]
[2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111]
[2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175]
[2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239]
[2240, 2241, 2242, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2251, 2252, 2253, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2273, 2274, 2275, 2276, 2277, 2278, 2279, 2280, 2281, 2282, 2283, 2284, 2285, 2286, 2287, 2288, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2302, 2303]
[2304, 2305, 2306, 2307, 2308, 2309, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2334, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349, 2350, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 2360, 2361, 2362, 2363, 2364, 2365, 2366, 2367]
[2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 2422, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2430, 2431]
[2432, 2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2441, 2442, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2463, 2464, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 2485, 2486, 2487, 2488, 2489, 2490, 2491, 2492, 2493, 2494, 2495]
[2496, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 2556, 2557, 2558, 2559]
[2560, 2561, 2562, 2563, 2564, 2565, 2566, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 2574, 2575, 2576, 2577, 2578, 2579, 2580, 2581, 2582, 2583, 2584, 2585, 2586, 2587, 2588, 2589, 2590, 2591, 2592, 2593, 2594, 2595, 2596, 2597, 2598, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2615, 2616, 2617, 2618, 2619, 2620, 2621, 2622, 2623]
[2624, 2625, 2626, 2627, 2628, 2629, 2630, 2631, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2641, 2642, 2643, 2644, 2645, 2646, 2647, 2648, 2649, 2650, 2651, 2652, 2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663, 2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674, 2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685, 2686, 2687]
[2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696, 2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707, 2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718, 2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729, 2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740, 2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751]
[2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762, 2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 2772, 2773, 2774, 2775, 2776, 2777, 2778, 2779, 2780, 2781, 2782, 2783, 2784, 2785, 2786, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2799, 2800, 2801, 2802, 2803, 2804, 2805, 2806, 2807, 2808, 2809, 2810, 2811, 2812, 2813, 2814, 2815]
[2816, 2817, 2818, 2819, 2820, 2821, 2822, 2823, 2824, 2825, 2826, 2827, 2828, 2829, 2830, 2831, 2832, 2833, 2834, 2835, 2836, 2837, 2838, 2839, 2840, 2841, 2842, 2843, 2844, 2845, 2846, 2847, 2848, 2849, 2850, 2851, 2852, 2853, 2854, 2855, 2856, 2857, 2858, 2859, 2860, 2861, 2862, 2863, 2864, 2865, 2866, 2867, 2868, 2869, 2870, 2871, 2872, 2873, 2874, 2875, 2876, 2877, 2878, 2879]
[2880, 2881, 2882, 2883, 2884, 2885, 2886, 2887, 2888, 2889, 2890, 2891, 2892, 2893, 2894, 2895, 2896, 2897, 2898, 2899, 2900, 2901, 2902, 2903, 2904, 2905, 2906, 2907, 2908, 2909, 2910, 2911, 2912, 2913, 2914, 2915, 2916, 2917, 2918, 2919, 2920, 2921, 2922, 2923, 2924, 2925, 2926, 2927, 2928, 2929, 2930, 2931, 2932, 2933, 2934, 2935, 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943]
[2944, 2945, 2946, 2947, 2948, 2949, 2950, 2951, 2952, 2953, 2954, 2955, 2956, 2957, 2958, 2959, 2960, 2961, 2962, 2963, 2964, 2965, 2966, 2967, 2968, 2969, 2970, 2971, 2972, 2973, 2974, 2975, 2976, 2977, 2978, 2979, 2980, 2981, 2982, 2983, 2984, 2985, 2986, 2987, 2988, 2989, 2990, 2991, 2992, 2993, 2994, 2995, 2996, 2997, 2998, 2999, 3000, 3001, 3002, 3003, 3004, 3005, 3006, 3007]
[3008, 3009, 3010, 3011, 3012, 3013, 3014, 3015, 3016, 3017, 3018, 3019, 3020, 3021, 3022, 3023, 3024, 3025, 3026, 3027, 3028, 3029, 3030, 3031, 3032, 3033, 3034, 3035, 3036, 3037, 3038, 3039, 3040, 3041, 3042, 3043, 3044, 3045, 3046, 3047, 3048, 3049, 3050, 3051, 3052, 3053, 3054, 3055, 3056, 3057, 3058, 3059, 3060, 3061, 3062, 3063, 3064, 3065, 3066, 3067, 3068, 3069, 3070, 3071]
[3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3080, 3081, 3082, 3083, 3084, 3085, 3086, 3087, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3095, 3096, 3097, 3098, 3099, 3100, 3101, 3102, 3103, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3112, 3113, 3114, 3115, 3116, 3117, 3118, 3119, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127, 3128, 3129, 3130, 3131, 3132, 3133, 3134, 3135]
[3136, 3137, 3138, 3139, 3140, 3141, 3142, 3143, 3144, 3145, 3146, 3147, 3148, 3149, 3150, 3151, 3152, 3153, 3154, 3155, 3156, 3157, 3158, 3159, 3160, 3161, 3162, 3163, 3164, 3165, 3166, 3167, 3168, 3169, 3170, 3171, 3172, 3173, 3174, 3175, 3176, 3177, 3178, 3179, 3180, 3181, 3182, 3183, 3184, 3185, 3186, 3187, 3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3199]
[3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209, 3210, 3211, 3212, 3213, 3214, 3215, 3216, 3217, 3218, 3219, 3220, 3221, 3222, 3223, 3224, 3225, 3226, 3227, 3228, 3229, 3230, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238, 3239, 3240, 3241, 3242, 3243, 3244, 3245, 3246, 3247, 3248, 3249, 3250, 3251, 3252, 3253, 3254, 3255, 3256, 3257, 3258, 3259, 3260, 3261, 3262, 3263]
[3264, 3265, 3266, 3267, 3268, 3269, 3270, 3271, 3272, 3273, 3274, 3275, 3276, 3277, 3278, 3279, 3280, 3281, 3282, 3283, 3284, 3285, 3286, 3287, 3288, 3289, 3290, 3291, 3292, 3293, 3294, 3295, 3296, 3297, 3298, 3299, 3300, 3301, 3302, 3303, 3304, 3305, 3306, 3307, 3308, 3309, 3310, 3311, 3312, 3313, 3314, 3315, 3316, 3317, 3318, 3319, 3320, 3321, 3322, 3323, 3324, 3325, 3326, 3327]
[3328, 3329, 3330, 3331, 3332, 3333, 3334, 3335, 3336, 3337, 3338, 3339, 3340, 3341, 3342, 3343, 3344, 3345, 3346, 3347, 3348, 3349, 3350, 3351, 3352, 3353, 3354, 3355, 3356, 3357, 3358, 3359, 3360, 3361, 3362, 3363, 3364, 3365, 3366, 3367, 3368, 3369, 3370, 3371, 3372, 3373, 3374, 3375, 3376, 3377, 3378, 3379, 3380, 3381, 3382, 3383, 3384, 3385, 3386, 3387, 3388, 3389, 3390, 3391]
[3392, 3393, 3394, 3395, 3396, 3397, 3398, 3399, 3400, 3401, 3402, 3403, 3404, 3405, 3406, 3407, 3408, 3409, 3410, 3411, 3412, 3413, 3414, 3415, 3416, 3417, 3418, 3419, 3420, 3421, 3422, 3423, 3424, 3425, 3426, 3427, 3428, 3429, 3430, 3431, 3432, 3433, 3434, 3435, 3436, 3437, 3438, 3439, 3440, 3441, 3442, 3443, 3444, 3445, 3446, 3447, 3448, 3449, 3450, 3451, 3452, 3453, 3454, 3455]

In [29]:
from torch.utils.data import DataLoader

from data.m2or import M2OR_Pairs
from dgllife.utils import SMILESToBigraph
from dgllife.utils import CanonicalAtomFeaturizer
from dgllife.utils import SMILESToBigraph

smiles_to_g = SMILESToBigraph(add_self_loop=True, node_featurizer=CanonicalAtomFeaturizer(),
                                edge_featurizer=None)

dataset = M2OR_Pairs(smiles_to_graph=smiles_to_g, 
        n_jobs=1, load=True)

Loading previously saved dgl graphs...

In [30]:
from dgllife.utils import ScaffoldSplitter, RandomSplitter

train_set, val_set, test_set = RandomSplitter.train_val_test_split(
    dataset, frac_train=0.8, frac_val=0.1, frac_test=0.1, random_state = 42)

In [39]:
import pandas as pd
m2or_df = pd.read_csv('data/datasets/M2OR_original_mol_OR_pairs.csv', sep = ';')
len(m2or_df)

46563

In [40]:
m2or_df

,mol_id,seq_id,Responsive,_DataQuality,num_unique_value_screen,canonicalSMILES,mutated_Sequence
0,m_0,s_29,1,ec50,NaN,CC1=CCC(CC1)C(=C)C,MRENNQSSTLEFILLGVTGQQEQEDFFYILFLFIYPITLIGNLLIV...
1,m_0,s_449,1,ec50,NaN,CC1=CCC(CC1)C(=C)C,MDQSNYSSLHGFILLGFSNHPKMEMILSGVVAIFYLITLVGNTAII...
2,m_0,s_539,0,ec50,NaN,CC1=CCC(CC1)C(=C)C,MDQSNYSSLHGFILLGFSNHPKMEMILSGVVAIFYLITLVGNTAII...
3,m_1,s_1,1,ec50,NaN,CC1=CCC(CC1=O)C(=C)C,MTEDNYSLTTEFILIGFSDHPDLKILLFLVLSTIYLVTMVGNLGLV...
4,m_1,s_1051,0,ec50,NaN,CC1=CCC(CC1=O)C(=C)C,MREENESSTTDFTLLGVTRQREQEYFFFILFLFIYPITVFGNMLII...
...,...,...,...,...,...,...,...
46558,m_99,s_443,1,secondaryScreening,4.0,C1=CC=C(C=C1)OC2=CC=CC=C2,MRENNQSSTLEFILLGVTGQQEQEDFFYILFLFIYPITLIGNLLIV...
46559,m_99,s_444,0,secondaryScreening,4.0,C1=CC=C(C=C1)OC2=CC=CC=C2,MRENNQSSTLEFILLGVTGQQEQEDFFYILFLFIYPITLIGNLLIV...
46560,m_99,s_449,0,secondaryScreening,4.0,C1=CC=C(C=C1)OC2=CC=CC=C2,MDQSNYSSLHGFILLGFSNHPKMEMILSGVVAIFYLITLVGNTAII...
46561,m_99,s_450,0,secondaryScreening,4.0,C1=CC=C(C=C1)OC2=CC=CC=C2,MDEANHSVVSEFVFLGLSDSRKIQLLLFLFFSVFYVSSLMGNLLIV...
46562,m_99,s_51,0,secondaryScreening,4.0,C1=CC=C(C=C1)OC2=CC=CC=C2,MDQSNYSSLHGFILLGFSNHPKMEMILSGVVAIFYLITLVGNTAII...

In [41]:
# have columns only be 'smiles','sequences','label'
perceiver_m2or_df = pd.DataFrame(columns=['smiles','sequence','label'])

perceiver_m2or_df['smiles'] = m2or_df['canonicalSMILES']
perceiver_m2or_df['sequence'] = m2or_df['mutated_Sequence']
perceiver_m2or_df['label'] = m2or_df['Responsive']

In [42]:
perceiver_m2or_df.head()

,smiles,sequence,label
0,CC1=CCC(CC1)C(=C)C,MRENNQSSTLEFILLGVTGQQEQEDFFYILFLFIYPITLIGNLLIV...,1
1,CC1=CCC(CC1)C(=C)C,MDQSNYSSLHGFILLGFSNHPKMEMILSGVVAIFYLITLVGNTAII...,1
2,CC1=CCC(CC1)C(=C)C,MDQSNYSSLHGFILLGFSNHPKMEMILSGVVAIFYLITLVGNTAII...,0
3,CC1=CCC(CC1=O)C(=C)C,MTEDNYSLTTEFILIGFSDHPDLKILLFLVLSTIYLVTMVGNLGLV...,1
4,CC1=CCC(CC1=O)C(=C)C,MREENESSTTDFTLLGVTRQREQEYFFFILFLFIYPITVFGNMLII...,0

In [43]:
# grab train indiices from m2or_df using train_set.indices, an array of indices
train_df = perceiver_m2or_df.iloc[train_set.indices]
val_df = perceiver_m2or_df.iloc[val_set.indices]
test_df = perceiver_m2or_df.iloc[test_set.indices]

In [44]:
train_df

,smiles,sequence,label
41293,CCC1C(=O)C(=C(O1)C)O,MTMENYSMAAQFVLDGLTQQAELQLPLFLLFLGIYVVTVVGNLGMI...,0
33748,CC(C)CCC(=O)O,MTETSLSSQCFPMSVLNNTIAEPLIFLLMGIPGLKATQYWISIPFC...,0
30441,CC(=O)C1=CC=CC=C1,MERVNETVVREVIFLGFSSLARLQQLLFVIFLLLYLFTLGTNAIII...,0
41445,CCCCCC(=O)O,MDSVNVSLVTEFLLVGLTHQPDRQIPLFLLFLAMYLVTALGNLGLI...,0
5139,CCC=CCCO,MNDDGKVNASSEGYFILVGFSNWPHLEVVIFVVVLIFYLMTLIGNL...,0
...,...,...,...
39937,CC1=C(C(CCC1)(C)C)C=CC(=O)C,MVGFNSNESSATYFILIGLPGLEEVQFWLAFPLCSLYLIAVLGNLT...,0
17290,CCCC(=O)O,MGFSNSWDIQIVHAALFFLVYLAAVIGNLLIIILTTLDVHLQTPMY...,0
42999,CCCCCCC(=CC1=CC=CC=C1)C=O,MKKMNYQEIGNYTKVTEFILVGLSRHPTSQSVVFWTLMFLYIVTLA...,0
760,CCCCCCO,MGDWNNSDAVEPIFILRGFPGLEYVHSWLSILFCLAYLVAFMGNVT...,0
19502,C=CCOC(=O)CC1=CC=CC=C1,MGNWSTVTEITLIAFPALLEIRISLFVVLVVTYTLTATGNITIISL...,0

In [45]:
train_df.to_csv('data/datasets/perceiver_M2OR_train.csv', sep = ',', index=False)
val_df.to_csv('data/datasets/perceiver_M2OR_val.csv', sep = ',', index=False)
test_df.to_csv('data/datasets/perceiver_M2OR_test.csv', sep = ',', index=False)